import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { RootWrapper } from "./rootWrapper";
import Header from "@/_components/header/header";
import Footer from "@/_components/footer/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Freejobalert Dashboard",
  // description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps): JSX.Element => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <div className="min-h-[calc(100vh-115px)]">
          <RootWrapper>{children}</RootWrapper>
        </div>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
